-- 12구역 멤버 일괄 입력

INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Hosung', 'Lee', '이호성', '1986-01-17', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '818-360-9070', 1);
UPDATE members SET address_line1 = '549 Via Estrada Unit A Laguna Woods, CA 92637' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Sangjin', 'Lee', '이상진', '1986-01-17', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '818-808-7228', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Chris', 'Lee', '이상준', '2008-03-30', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '310-713-1358', 1);
UPDATE members SET address_line1 = '61 Copper Leaf Irvine, CA 92602' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Roxanne', 'Lee', '이현경', '2007-11-03', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '310-738-8220', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Jong', 'Nha', '나종성', '2018-05-18', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '213-663-9349', 1);
UPDATE members SET address_line1 = '13106 St. Andrews Dr. 239E Seal Beach, CA 90740' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Connie', 'Nha', '나학임', '1986-08-09', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-222-7478', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Ho', 'Lee', '이호형', '9/00/2017', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-625-7773', 1);
UPDATE members SET address_line1 = '7777 Valley View St D103 La Palma CA 90623' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Estella', 'Lee', '이선희', '2006-09-20', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-625-7774', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Terry', 'Kim', '김택회', '2014-09-25', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-931-7411', 1);
UPDATE members SET address_line1 = '14022 Elmbrook Dr La Mirada CA 90638' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Mia', 'Jun', '전미애', '2014-04-25', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-931-6721', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Alex', 'Cho', '조광래', '80/00/1996', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-823-7704', 1);
UPDATE members SET address_line1 = '5840 Cedar Spring Ct, Chino Hills' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Lois', 'Yang', '양느미', '12/00/2002', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-823-7720', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Alex', 'Cho', '조현율', '07/00/2019', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Aden', 'Cho', '조현유', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Billy', 'Oh', '오상민', '2007-05-21', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '562-640-7317', 1);
UPDATE members SET address_line1 = '1884 Berkshire Dr Fullerton ' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Hailey', 'Kang', '강혜민', '1996-02-25', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '657-632-7299', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Chris', 'Oh', '오의찬', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Danny', 'Oh', '오윤호', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Steve', 'Choi', '최환정', '2019-11-08', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '916-798-3886', 1);
UPDATE members SET address_line1 = '21209 Bloomfield Ave Apt #18 Lakewood 90715' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'John', 'Cho', '조인준', '2018-11-02', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '562-284-9741', 1);
UPDATE members SET address_line1 = '852 W Glenwood Cr Fullerton' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Sunami', 'Chun', '전수나미', '2/00/2009', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '562-451-9184', 1);
UPDATE members SET address_line1 = '2531 biscayne Pl Fullerton' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Ligia', 'Lee', '이지애', '7/00/93', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '657-631-2196', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Caio', 'Chun', '전까요', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Maya', 'Chun', '전마야', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Jung', 'Yoo', '유정옥', '2010-01-01', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-402-4323', 1);
UPDATE members SET address_line1 = '11182 Mount Dr Garden Grove 92840' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Grace', 'Ryu', '그레이스류', '8/00/1993', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-323-5080', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'H', 'Doe', '혜미', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Misuk', 'Oh', '오미숙', '1989-07-15', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '310-817-3736', 1);
UPDATE members SET address_line1 = '1715 W 158th Apt 414 Gardena 90247' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Cindy', 'Kim', '김신희', '2018-07-03', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-321-7590', 1);
UPDATE members SET address_line1 = '17351 E Main St #36 La Puente CA 91744' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Eunhee', 'Kim', '김은희', '', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '310-866-2626', 1);
UPDATE members SET address_line1 = '783 gatun st unit 319 San Padro CA 90731' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Sungyun', 'Im', '임성윤', '2007-01-14', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '657-319-5516', 1);
UPDATE members SET address_line1 = '1001 Starbuck St K302 Fullerton 92833' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Jinwoo', 'Lee', '이진우', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Sunny', 'So', '서명순', '2007-01-03', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '626-203-7457', 1);
UPDATE members SET address_line1 = '17351 E Main St #65 La Puente CA 91744' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Brian', 'Shin', '신우영', '2004-07-04', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-673-1203', 1);
UPDATE members SET address_line1 = '25 Palatine Irvine' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'L', 'Doe', '리즈', '', '성도', '봉사자', '활동', 'US');
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Ryan', 'Lee', '라이언', '2/00/2018', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '562-565-7009', 1);
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Joyce', 'Shin', '조이스', '3-00', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-975-1004', 1);
UPDATE members SET address_line1 = '33 Copper Leaf Irvine' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Jean', 'Choi', '최서영', '9/00/2003', '성도', '봉사자', '활동', 'US');
UPDATE members SET address_line1 = '2334 Hosp Way Unit 310 Carlsbad CA 92008' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'Willy', 'So', '윌리서', '3/00/2020', '성도', '봉사자', '활동', 'US');
UPDATE members SET address_line1 = '17351 E Main St #36 La Puente CA 91744' WHERE member_id = last_insert_rowid();
INSERT INTO members (church_id, first_name, last_name, korean_name, birth_date, member_type, employment_type, status, country) VALUES (1, 'alice', 'Lee', '이예원', '2012-09-17', '성도', '봉사자', '활동', 'US');
INSERT INTO member_contacts (member_id, contact_type, value, is_primary) VALUES (last_insert_rowid(), 'mobile', '714-858-9363', 1);
UPDATE members SET address_line1 = '6510 Jekyll Way Cypress, CA 90630' WHERE member_id = last_insert_rowid();
